question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
    {"text": "An octopus has three hearts.", "answer": "True"},
    {"text": "The capital of Australia is Sydney.", "answer": "False"},
    {"text": "Bananas grow on trees.", "answer": "False"},
    {"text": "Humans share about 60% of their DNA with bananas.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "Lightning never strikes the same place twice.", "answer": "False"},
    {"text": "Goldfish only have a memory span of three seconds.", "answer": "False"},
    {"text": "The human nose and ears continue to grow throughout a person’s life.", "answer": "True"},
    {"text": "There are more stars in the universe than grains of sand on Earth.", "answer": "True"},
    {"text": "Walt Disney was cryogenically frozen.", "answer": "False"},
    {"text": "Adult humans have fewer bones than babies.", "answer": "True"},
    {"text": "The longest hiccuping spree lasted over 60 years.", "answer": "True"},
    {"text": "The heart of a shrimp is located in its head.", "answer": "True"},
    {"text": "The Eiffel Tower can grow taller in the summer.", "answer": "True"},
    {"text": "A sneeze travels out of your mouth at over 160 km/h.", "answer": "True"},
    {"text": "Vikings wore horned helmets in battle.", "answer": "False"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "Slugs have four noses.", "answer": "True"},
    {"text": "Bats are blind.", "answer": "False"},
    {"text": "Water spirals down the drain in opposite directions in the Northern and Southern Hemispheres.",
     "answer": "False"},
    {"text": "Humans can distinguish over a trillion different smells.", "answer": "True"},
    {"text": "The fingerprints of a koala are almost indistinguishable from a human's.", "answer": "True"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "Camels store water in their humps.", "answer": "False"},
    {"text": "There’s a species of jellyfish that can potentially live forever.", "answer": "True"},
    {"text": "The Empire State Building has its own zip code.", "answer": "True"},
    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "A group of flamingos is called a 'flamboyance'.", "answer": "True"},
    {"text": "Dolphins sleep with one eye open.", "answer": "True"},
    {"text": "The dot over the letters 'i' and 'j' is called a tittle.", "answer": "True"},
    {"text": "An ostrich’s eye is bigger than its brain.", "answer": "True"},
    {"text": "A bolt of lightning is hotter than the surface of the sun.", "answer": "True"},
    {"text": "Oxford University is older than the Aztec Empire.", "answer": "True"},
    {"text": "Peanuts grow on trees.", "answer": "False"},
    {"text": "There are more fake flamingos in the world than real ones.", "answer": "True"},
    {"text": "The word 'news' is an acronym for 'North, East, West, South'.", "answer": "False"},
    {"text": "The inventor of the Pringles can is buried in one.", "answer": "True"},
    {"text": "A crocodile cannot stick its tongue out.", "answer": "True"},
    {"text": "Penguins can fly.", "answer": "False"},
    {"text": "The first oranges weren’t orange.", "answer": "True"},
    {"text": "Sea otters hold hands while they sleep.", "answer": "True"},
    {"text": "A day on Venus is longer than a year on Venus.", "answer": "True"},
    {"text": "Bubble wrap was originally intended to be wallpaper.", "answer": "True"},
    {"text": "The inventor of the microwave appliance only received $10 for his discovery.", "answer": "True"},
    {"text": "Humans can breathe and swallow at the same time.", "answer": "False"},
    {"text": "There are more trees on Earth than stars in the Milky Way.", "answer": "True"},
    {"text": "Napoleon was extremely short.", "answer": "False"},
    {"text": "You can’t hum while holding your nose.", "answer": "True"},
    {"text": "The Great Fire of London in 1666 destroyed most of the city.", "answer": "False"},
    {"text": "The unicorn is a mythical creature from Greek mythology.", "answer": "False"},
    {"text": "Cats have fewer toes on their back paws.", "answer": "True"},
    {"text": "The longest place name in the world is 85 characters long.", "answer": "True"},
    {"text": "Elephants can jump.", "answer": "False"},
    {"text": "Humans are the only animals that blush.", "answer": "True"},
    {"text": "The speed of a computer mouse is measured in 'Mickeys'.", "answer": "True"},
    {"text": "There is no gravity in space.", "answer": "False"},
    {"text": "The first computer virus was created in the 2000s.", "answer": "False"},
    {"text": "Alaska is the westernmost, easternmost, and northernmost state in the US.", "answer": "True"},
    {"text": "Kangaroos cannot walk backwards.", "answer": "True"},
    {"text": "There is a species of fungus that turns ants into zombies.", "answer": "True"},
    {"text": "A snail can sleep for three years.", "answer": "True"},
    {"text": "Humans glow in the dark.", "answer": "True"},
    {"text": "You can’t see the Great Wall of China from the moon.", "answer": "True"},
    {"text": "Rabbits can see behind them without turning their heads.", "answer": "True"},
    {"text": "Wombat poop is cube-shaped.", "answer": "True"},
    {"text": "The shortest war in history lasted 38 minutes.", "answer": "True"},
    {"text": "Birds are dinosaurs.", "answer": "True"},
    {"text": "Shaving makes hair grow back thicker.", "answer": "False"},
    {"text": "Jellyfish have no brains.", "answer": "True"},
    {"text": "Antarctica is the driest place on Earth.", "answer": "True"},
    {"text": "Tomatoes were once considered poisonous.", "answer": "True"},
    {"text": "Bees can recognise human faces.", "answer": "True"},
    {"text": "Octopuses have blue blood.", "answer": "True"},
    {"text": "The moon is slowly moving away from the Earth.", "answer": "True"},
    {"text": "Humans can survive without a spleen.", "answer": "True"},
    {"text": "Polar bear fur is white.", "answer": "False"},
    {"text": "A cockroach can live several weeks without its head.", "answer": "True"},
    {"text": "Your stomach gets a new lining every 3 to 4 days.", "answer": "True"},
    {"text": "Sound travels faster in air than in water.", "answer": "False"},
    {"text": "The inventor of Velcro got the idea from burrs sticking to his dog.", "answer": "True"},
    {"text": "Birds are not real.", "answer": "False"},
    {"text": "Mars has blue sunsets.", "answer": "True"},
    {"text": "There are more chickens on Earth than people.", "answer": "True"},
    {"text": "Spiders are insects.", "answer": "False"},
    {"text": "The longest English word has over 180,000 letters.", "answer": "True"},
    {"text": "The word 'robot' comes from a Czech word meaning 'forced labour'.", "answer": "True"},
    {"text": "Australia is wider than the moon.", "answer": "True"},
    {"text": "Your fingernails grow faster on your dominant hand.", "answer": "True"},
    {"text": "The tongue is the strongest muscle in the human body.", "answer": "False"},
    {"text": "You can’t burp in space.", "answer": "True"},
    {"text": "Sharks are older than trees.", "answer": "True"},
    {"text": "The word 'quiz' was invented as part of a bet.", "answer": "True"},
    {"text": "Avocados are vegetables.", "answer": "False"},
    {"text": "The name of all continents ends with the same letter it starts with.", "answer": "True"},
    {"text": "There’s a basketball court on the top floor of the Eiffel Tower.", "answer": "False"},
    {"text": "The total weight of all ants on Earth is roughly equal to the weight of all humans.", "answer": "True"},
    {"text": "The longest time between two twins being born is 87 days.", "answer": "True"},
    {"text": "Cows have best friends and get stressed when separated.", "answer": "True"}
]